In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('./sales_data.csv')
df.columns

Index(['Order Date', 'Order ID', 'Product', 'Product_ean', 'catégorie',
       'Purchase Address', 'Quantity Ordered', 'Price Each', 'Cost price',
       'turnover', 'margin'],
      dtype='object')

In [4]:
df.head()

,Order Date,Order ID,Product,Product_ean,catégorie,Purchase Address,Quantity Ordered,Price Each,Cost price,turnover,margin
0,2019-01-22 21:25:00,141234,iPhone,5.638009e+12,Vêtements,"944 Walnut St, Boston, MA 02215",1,700.00,231.0000,700.00,469.0000
1,2019-01-28 14:15:00,141235,Lightning Charging Cable,5.563320e+12,Alimentation,"185 Maple St, Portland, OR 97035",1,14.95,7.4750,14.95,7.4750
2,2019-01-17 13:33:00,141236,Wired Headphones,2.113973e+12,Vêtements,"538 Adams St, San Francisco, CA 94016",2,11.99,5.9950,23.98,11.9900
3,2019-01-05 20:33:00,141237,27in FHD Monitor,3.069157e+12,Sports,"738 10th St, Los Angeles, CA 90001",1,149.99,97.4935,149.99,52.4965
4,2019-01-25 11:59:00,141238,Wired Headphones,9.692681e+12,Électronique,"387 10th St, Austin, TX 73301",1,11.99,5.9950,11.99,5.9950

In [5]:
# check for duplicates
df.duplicated().sum()

0

In [6]:
# split purchase address
x = df['Purchase Address'].str.split(',')
df['Purchase City'] = x.str.get(1)
df['Purchase State'] = x.str.get(2).str.split(' ').str.get(1)
df.head()

,Order Date,Order ID,Product,Product_ean,catégorie,Purchase Address,Quantity Ordered,Price Each,Cost price,turnover,margin,Purchase City,Purchase State
0,2019-01-22 21:25:00,141234,iPhone,5.638009e+12,Vêtements,"944 Walnut St, Boston, MA 02215",1,700.00,231.0000,700.00,469.0000,Boston,MA
1,2019-01-28 14:15:00,141235,Lightning Charging Cable,5.563320e+12,Alimentation,"185 Maple St, Portland, OR 97035",1,14.95,7.4750,14.95,7.4750,Portland,OR
2,2019-01-17 13:33:00,141236,Wired Headphones,2.113973e+12,Vêtements,"538 Adams St, San Francisco, CA 94016",2,11.99,5.9950,23.98,11.9900,San Francisco,CA
3,2019-01-05 20:33:00,141237,27in FHD Monitor,3.069157e+12,Sports,"738 10th St, Los Angeles, CA 90001",1,149.99,97.4935,149.99,52.4965,Los Angeles,CA
4,2019-01-25 11:59:00,141238,Wired Headphones,9.692681e+12,Électronique,"387 10th St, Austin, TX 73301",1,11.99,5.9950,11.99,5.9950,Austin,TX

In [7]:
# show all products
print(df['Product'].unique())
print()
# show all categories
print(df['catégorie'].unique())

['iPhone' 'Lightning Charging Cable' 'Wired Headphones' '27in FHD Monitor'
 'AAA Batteries (4-pack)' '27in 4K Gaming Monitor' 'USB-C Charging Cable'
 'Bose SoundSport Headphones' 'Apple Airpods Headphones'
 'Macbook Pro Laptop' 'Flatscreen TV' 'Vareebadd Phone'
 'AA Batteries (4-pack)' 'Google Phone' '20in Monitor'
 '34in Ultrawide Monitor' 'ThinkPad Laptop' 'LG Dryer'
 'LG Washing Machine']

['Vêtements' 'Alimentation' 'Sports' 'Électronique']

In [12]:
# fix wrong category data using ChatGPT
import openai
import json

with open("credentials.json") as config_file:
  config = json.load(config_file)
  USERNAME = config['USERNAME']
  APIKEY = config['APIKEY']
  ORGANIZATION = config['ORGANIZATION']


openai.organization = ORGANIZATION
openai.api_key = APIKEY

messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Help me categorize my products. Please return a a Python dictionary without any other text that I can easily access in the format {'PRODUCT':'CATEGORY'}. Here is the list: " + str(df['Product'].unique())},
    ]
# openai.Model.list()

response = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=messages,
)
response

<OpenAIObject chat.completion id=chatcmpl-7wA4T6xf7Acnfm05Vz3bUPBeuksxe at 0x157dab3b0> JSON: {
  "id": "chatcmpl-7wA4T6xf7Acnfm05Vz3bUPBeuksxe",
  "object": "chat.completion",
  "created": 1694096093,
  "model": "gpt-3.5-turbo-0613",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "Here is a Python dictionary categorizing your products:\n\n```\n{\n    'iPhone': 'Electronics',\n    'Lightning Charging Cable': 'Electronics',\n    'Wired Headphones': 'Electronics',\n    '27in FHD Monitor': 'Electronics',\n    'AAA Batteries (4-pack)': 'Electronics',\n    '27in 4K Gaming Monitor': 'Electronics',\n    'USB-C Charging Cable': 'Electronics',\n    'Bose SoundSport Headphones': 'Electronics',\n    'Apple Airpods Headphones': 'Electronics',\n    'Macbook Pro Laptop': 'Electronics',\n    'Flatscreen TV': 'Electronics',\n    'Vareebadd Phone': 'Electronics',\n    'AA Batteries (4-pack)': 'Electronics',\n    'Google Phone': 'Electronics',\n    '20in Monitor': 'Electronics',\n    '34in Ultrawide Monitor': 'Electronics',\n    'ThinkPad Laptop': 'Electronics',\n    'LG Dryer': 'Appliances',\n    'LG Washing Machine': 'Appliances'\n}\n```\n\nThe products are categorized into two categories: 'Electronics' and 'Appliances'."
      },
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 173,
    "completion_tokens": 251,
    "total_tokens": 424
  }
}

In [36]:
# print(response['choices'][0]['message']['content'])
temp = response['choices'][0]['message']['content'].split('```')[1]
print(temp)

{
    'iPhone': 'Electronics',
    'Lightning Charging Cable': 'Electronics',
    'Wired Headphones': 'Electronics',
    '27in FHD Monitor': 'Electronics',
    'AAA Batteries (4-pack)': 'Electronics',
    '27in 4K Gaming Monitor': 'Electronics',
    'USB-C Charging Cable': 'Electronics',
    'Bose SoundSport Headphones': 'Electronics',
    'Apple Airpods Headphones': 'Electronics',
    'Macbook Pro Laptop': 'Electronics',
    'Flatscreen TV': 'Electronics',
    'Vareebadd Phone': 'Electronics',
    'AA Batteries (4-pack)': 'Electronics',
    'Google Phone': 'Electronics',
    '20in Monitor': 'Electronics',
    '34in Ultrawide Monitor': 'Electronics',
    'ThinkPad Laptop': 'Electronics',
    'LG Dryer': 'Appliances',
    'LG Washing Machine': 'Appliances'
}

In [40]:
# replace single quotes in temp with double quotes
temp = temp.replace("'", '"')
print(temp)

{
    "iPhone": "Electronics",
    "Lightning Charging Cable": "Electronics",
    "Wired Headphones": "Electronics",
    "27in FHD Monitor": "Electronics",
    "AAA Batteries (4-pack)": "Electronics",
    "27in 4K Gaming Monitor": "Electronics",
    "USB-C Charging Cable": "Electronics",
    "Bose SoundSport Headphones": "Electronics",
    "Apple Airpods Headphones": "Electronics",
    "Macbook Pro Laptop": "Electronics",
    "Flatscreen TV": "Electronics",
    "Vareebadd Phone": "Electronics",
    "AA Batteries (4-pack)": "Electronics",
    "Google Phone": "Electronics",
    "20in Monitor": "Electronics",
    "34in Ultrawide Monitor": "Electronics",
    "ThinkPad Laptop": "Electronics",
    "LG Dryer": "Appliances",
    "LG Washing Machine": "Appliances"
}

In [41]:
product_categories = json.loads(temp)
product_categories

{'iPhone': 'Electronics',
 'Lightning Charging Cable': 'Electronics',
 'Wired Headphones': 'Electronics',
 '27in FHD Monitor': 'Electronics',
 'AAA Batteries (4-pack)': 'Electronics',
 '27in 4K Gaming Monitor': 'Electronics',
 'USB-C Charging Cable': 'Electronics',
 'Bose SoundSport Headphones': 'Electronics',
 'Apple Airpods Headphones': 'Electronics',
 'Macbook Pro Laptop': 'Electronics',
 'Flatscreen TV': 'Electronics',
 'Vareebadd Phone': 'Electronics',
 'AA Batteries (4-pack)': 'Electronics',
 'Google Phone': 'Electronics',
 '20in Monitor': 'Electronics',
 '34in Ultrawide Monitor': 'Electronics',
 'ThinkPad Laptop': 'Electronics',
 'LG Dryer': 'Appliances',
 'LG Washing Machine': 'Appliances'}

In [47]:
# enter product categories into dataframe
df['Category'] = df['Product'].map(product_categories)
df['Capital'] = df['Quantity Ordered']*df['Cost price']

# drop catégorie
df.drop('catégorie', axis=1, inplace=True)

In [48]:
df.head()

,Order Date,Order ID,Product,Product_ean,Purchase Address,Quantity Ordered,Price Each,Cost price,turnover,margin,Purchase City,Purchase State,Category,Capital
0,2019-01-22 21:25:00,141234,iPhone,5.638009e+12,"944 Walnut St, Boston, MA 02215",1,700.00,231.0000,700.00,469.0000,Boston,MA,Electronics,231.0000
1,2019-01-28 14:15:00,141235,Lightning Charging Cable,5.563320e+12,"185 Maple St, Portland, OR 97035",1,14.95,7.4750,14.95,7.4750,Portland,OR,Electronics,7.4750
2,2019-01-17 13:33:00,141236,Wired Headphones,2.113973e+12,"538 Adams St, San Francisco, CA 94016",2,11.99,5.9950,23.98,11.9900,San Francisco,CA,Electronics,11.9900
3,2019-01-05 20:33:00,141237,27in FHD Monitor,3.069157e+12,"738 10th St, Los Angeles, CA 90001",1,149.99,97.4935,149.99,52.4965,Los Angeles,CA,Electronics,97.4935
4,2019-01-25 11:59:00,141238,Wired Headphones,9.692681e+12,"387 10th St, Austin, TX 73301",1,11.99,5.9950,11.99,5.9950,Austin,TX,Electronics,5.9950

In [50]:
# export
df.to_csv('./sales_data_cleaned.csv', index=False)